[project]
name = "make-civic-wallpaper"
version = "0.1.0"
description = "A CLI command to create compatible wallpapers for your 2018 Honda Civic LX!"
authors = [
    { name = "Ryn Stewart", email = "rynstwrt17@gmail.com" }
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pillow (>=12.3.0,<13.0.0)",
    "typer (>=0.27.2,<0.28.0)",
    "imageio (>=2.38.0,<3.0.0)",
    "rich (>=15.0.0,<16.0.0)",
    "universal-pathlib (>=0.3.10,<0.4.0)",
    "click (>=8.5.0,<9.0.0)",
    "requests (>=2.34.2,<3.0.0)",
    "aiohttp (>=3.14.3,<4.0.0)",
]


[project.scripts]
makecivicwallpaper = "make_civic_wallpaper.main:app"
civicwallpaper = "make_civic_wallpaper.main:app"
mcw = "make_civic_wallpaper.main:app"


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"