[project]
name = "civic_wallpaper"
version = "0.1.0"
description = ""
authors = [
    { name = "Ryn Stewart", email = "rynstwrt17@gmail.com" }
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pillow (>=12.3.0,<13.0.0)",
    "typer (>=0.27.2,<0.28.0)",
]


[project.scripts]
makecivicwallpaper = "civic_wallpaper.civic_wallpaper:app"
ryntest = "civic_wallpaper:test"


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"